### ISSUE TITLE
Add rosezipper to Stackage lts-12.18 ?

### ISSUE THREAD

**Issue by clojj** [yav/haskell-zipper#1]
Hi,
would you be interested in a PR to add this package to stackage lts-12.18 ?
(checked locally and it works fine with lts-12.18)

it would be these steps
https://github.com/commercialhaskell/stackage/blob/master/MAINTAINERS.md#adding-a-package

**Comment by yav** [comment]
Ah wow, it's been a long time since I've look at this code :)    Sure, PR away!

**Comment by clojj** [comment]
Do you want to add the entry to stackage yourself (build-constraints.yaml) ?
as recommended here...
https://github.com/commercialhaskell/stackage/blob/master/MAINTAINERS.md#adding-a-package

**Comment by clojj** [comment]
@yav would you prefer staying the maintainer of rosezipper ?
otherwise I can offer to be the maintainer (at least for stackage)

**Comment by yav** [comment]
Hi, sorry, I don't really use stackage so I haven't read the instructions on how to add the package there.

If you want to upload it yourself, please go ahead---I'd be happy for you to be the maintainer for stackage.  I don't imagine this code needs a lot of maintaining, but if you need some changes just make an issue or if you have the time a PR, and I'd be happy to make the changes.

**Comment by clojj** [comment]
good news
it has been added to nightly + lts-12.20

**Comment by yav** [comment]
Cool, thanks!  I guess I'll close this for now, please feel free to make a PR if anything needs to be changed.
